Fix configuration for pytest 9 (#74)
Before this change, pytest 9 failed with:

```
TypeError: pyproject.toml: config option 'addopts' expects a list for type 'args', got str: '--cov --cov-report=html --cov-fail-under=100'
```

See https://github.com/pytest-dev/pytest/issues/13743.